---
title: "PM566 Final Project"
author: "Mingxi Xu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

This is my PM566 Final Project website. I will showcase a few interactive visuals here.

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
library(stringr)
library(sjPlot)
library(ggthemes)
library(scales)
library(ggwordcloud)
library(ggpubr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```


```{r,echo=FALSE}
df = fread("data/national-history.csv")
#overview = df[1,c("date","totalTestResults","positive","recovered","death")]
#colnames(overview) = c("date","total tests", "accumulated confirmed case numbers", "accumulated recoveries", "accumulated deaths")
#kable(overview)
df_melted = melt(df, id.vars="date",measure.vars=c("totalTestResultsIncrease","positiveIncrease","deathIncrease"), value.name="case")
levels(df_melted$variable) <- c("New COVID-19 Tests", "New Positive Cases", "New Death Cases")
p <- df_melted %>%
   ggplot(mapping= aes(x=date, y=case))+geom_line(aes(color=variable))+geom_area(alpha=0.5,aes(fill=variable))+
   scale_x_date(date_breaks = "1 month", minor_breaks = "1 week", labels = date_format("%b-%d"))+
   labs(x='Date',y=NULL)+
   theme(axis.text.x = element_text(angle = 0))+
   theme(plot.title = element_text(hjust = 0.5),legend.position = "none")+
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
   theme(panel.background = element_blank(), axis.line = element_line(colour =    
   "black"))+facet_wrap(.~variable,scales = "free_y",ncol=1)+
   ggtitle("COVID-19 Pandemic Tendencies")
ggplotly(p)
```


```{r,echo=FALSE}
df_case = fread("./data/cases_by_age_group.csv")
df_death = fread("./data/deaths_by_age_group.csv")
df_case$label = paste(df_case$Count, "(", df_case$Percentage, "%)", sep="")
df_death$label = paste(df_death$Count, "(", df_death$Percentage, "%)", sep="")
df_case$percent = df_case$Count*100/sum(df_case$Count)
df_death$percent = df_death$Count*100/sum(df_death$Count)
df_case$type  = "COVID-19 cases"
df_death$type = "COVID-19 deaths"
df = rbind(df_case,df_death)
colnames(df)[1] = "age"
df$age = factor(df$age)
levels(df$age) = c("0 - 4 Years","5 - 17 Years","18 - 29 Years","30 - 39 Years", "40 - 49 Years","50 - 64 Years","65 - 74 Years","75 - 84 Years","85+ Years")
p <- ggplot(df,aes(x=age, y=percent))+geom_bar(stat="identity",fill="Orange")+
    geom_smooth(aes(group=1), method = "loess", se = FALSE)+ theme(axis.text.x = element_text(angle =    45,vjust=15))+labs(x=NULL)+facet_wrap(.~type)+
   theme(panel.background = element_blank(), axis.line = element_line(colour =    
   "black"),plot.title = element_text(hjust = 0.5))+ggtitle("Infection status of different age groups")
ggplotly(p)
```

```{r, echo=FALSE}
df2 = data.table::fread("data/states_current.csv")
df_popu = data.table::fread("./data/us_census_2018_population_estimates_states.csv")
df3 <- df2 %>%
    select(state, state, positive) %>%
    left_join(df_popu, by="state")
df3$rate = df3$positive/df3$population
df3 <- df3 %>% select(state,rate, state_name)
colnames(df3) <- c("state","rate","state.name")
df3$hover <- with(df3, paste(state.name, '<br>', "Inection rate:", rate))
p3 <- plot_geo(df3) %>%
  add_trace(
    z = ~rate, text = ~hover, span=I(0),
    locations = ~state, locationmode="USA-states") %>%
  layout(geo=list(
                  scope = 'usa',
                  projection = list(type = 'albers usa'),
                  lakecolor = toRGB('white')
                 ),
         title=paste('population infection rate(20201111) ','<br>(Hover for value)')
        )
p3
```

